name: data_analyzer_app
description: 数据分析仪，离线购买情况号码分析与相似组合生成 APK。
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: 6.2.1
  path_provider: 2.1.4
  share_plus: 9.0.0
  collection: ^1.18.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
